Models/TbCupom.cs
using System;
using System.Collections.Generic;

namespace MyWebCupom.Models;

public partial class TbCupom
{
    public int Id { get; set; }

    public string Title { get; set; } = null!;

    public string ?UrlCupom { get; set; }
}

Controllers/TbCupomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyWebCupom.Models;

namespace MyWebCupom.Controllers
{
    public class TbCupomsController : Controller
    {
        private readonly DbTechchallengeContext _context;

        private readonly BlobServiceClient _blobServiceClient;

        private readonly string connectionString = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("ConnectionStrings")["AzureBlobStorage"];

        private readonly string pathImageAzure = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("ConnectionStrings")["PathImgAzure"];

        public TbCupomsController(DbTechchallengeContext context)
        {
            _context = context;
            _blobServiceClient = new BlobServiceClient(connectionString);
        }

        // GET: TbCupoms
        public async Task<IActionResult> Index()
        {
              return _context.TbCupoms != null ? 
                          View(await _context.TbCupoms.ToListAsync()) :
                          Problem("Entity set 'DbTechchallengeContext.TbCupoms'  is null.");
        }

        // GET: TbCupoms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TbCupoms == null)
            {
                return NotFound();
            }

            var tbCupom = await _context.TbCupoms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbCupom == null)
            {
                return NotFound();
            }
            else
            {
                tbCupom.UrlCupom = pathImageAzure + tbCupom.UrlCupom;
            }
            return View(tbCupom);
        }

        // GET: TbCupoms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TbCupoms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title")] TbCupom tbCupom)
        {
            if (ModelState.IsValid)
            {

                var httpRequest = HttpContext.Request;

                if (httpRequest.Form.Files.Count > 0)
                {
                    const int fileIndex = 0;

                    IFormFile postedFile = httpRequest.Form.Files[fileIndex];

                    var containerInstance = _blobServiceClient.GetBlobContainerClient("techticketimage");

                    var fileName = Guid.NewGuid() + postedFile.FileName;

                    var blobInstance = containerInstance.GetBlobClient(fileName);

                    await blobInstance.UploadAsync(postedFile.OpenReadStream());

                    tbCupom.UrlCupom = fileName;                    

                }
                _context.Add(tbCupom);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tbCupom);
        }

        // GET: TbCupoms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TbCupoms == null)
            {
                return NotFound();
            }

            var tbCupom = await _context.TbCupoms.FindAsync(id);            

            if (tbCupom == null)
            {
                return NotFound();
            }            
            return View(tbCupom);
        }

        // POST: TbCupoms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,UrlCupom")] TbCupom tbCupom)
        {
            if (id != tbCupom.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {                    
                    _context.Update(tbCupom);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbCupomExists(tbCupom.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tbCupom);
        }

        // GET: TbCupoms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TbCupoms == null)
            {
                return NotFound();
            }

            var tbCupom = await _context.TbCupoms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbCupom == null)
            {
                return NotFound();
            }

            return View(tbCupom);
        }

        // POST: TbCupoms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TbCupoms == null)
            {
                return Problem("Entity set 'DbTechchallengeContext.TbCupoms'  is null.");
            }
            var tbCupom = await _context.TbCupoms.FindAsync(id);
            if (tbCupom != null)
            {
                _context.TbCupoms.Remove(tbCupom);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbCupomExists(int id)
        {
          return (_context.TbCupoms?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/TbCupoms/Create.cshtml
@model MyWebCupom.Models.TbCupom

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TbCupom</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "TbCupoms", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>            
            <div class="row">
                <label for="file">Imagem Cupon:</label>
                <input type="file" name="file" id="file" accept="image/*" capture />
                <br />
                <input type="submit" value="Upload File" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/TbCupoms/Delete.cshtml
@model MyWebCupom.Models.TbCupom

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TbCupom</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlCupom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlCupom)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/TbCupoms/Details.cshtml
@model MyWebCupom.Models.TbCupom

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TbCupom</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            CUPOM
            @*@Html.DisplayNameFor(model => model.UrlCupom)*@
        </dt>
        <dd class = "col-sm-10">
            @*@Html.DisplayFor(model => model.UrlCupom)*@
            @{
                string urladdress = Model.UrlCupom.ToString();                
                string pathAzure = System.Configuration.ConfigurationManager.AppSettings["PathImgAzure"];
            }
            <img src="@Url.Content(@pathAzure+@urladdress)" alt="CUPOM" width="150px" height="150px" />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/TbCupoms/Edit.cshtml
@model MyWebCupom.Models.TbCupom

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TbCupom</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlCupom" class="control-label"></label>
                <input asp-for="UrlCupom" class="form-control" />
                <span asp-validation-for="UrlCupom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TbCupoms/Index.cshtml
@model IEnumerable<MyWebCupom.Models.TbCupom>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UrlCupom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrlCupom)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>